export default class CommonConstants {
  /**
   * The text high
   */
  static TEXT_HEIGHT: number = 50;

  /**
   * The text width
   */
  static DEFAULT_MARGIN: number = 30;

  /**
   * Full the width.
   */
  static FULL_WIDTH: string = '100%';

  /**
   * Full the height.
   */
  static FULL_HEIGHT: string = '100%';

  /**
   * Default fontSize
   */
  static DEFAULT_FONT_SIZE: number = 30;

  /*
   * Log Domain
   * */
  static DOMAIN: number = 0x0000;
}